name: Bot deploy workflow
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run command on remote server
        uses: D3rHase/ssh-command-action@v0.3
        with:
          host: ${{secrets.SSH_HOST}}
          port: ${{secrets.SSH_PORT}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout main;
            git pull;
#            docker-compose --file docker-compose.yml down;
#            docker-compose --file docker-compose.yml up -d;
            docker-compose build;
            docker-compose up --force-recreate -d;
            docker system prune --all --force;
